---
title: "RFC_project_overview"
author: "Madlen Wilmes"
date: "6/22/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Real Food Campaign - Project Overview

URL: [lab.realfoodcampaign.org](lab.realfoodcampaign.org)

- world-wide initiative of scientists to investigate nutrient content of produce in actual food supply chain (not controlled environment)
- measured compounds: antioxidants and minerals
- focus on data quantity, quality, cost, and utility
- connecting soil and food quality using low-cost, high throughput food and soil survey with nutrient data
- lab tests of produce and soil
- open science: all data publicly accessible, but anonymized to protect privacy


## Collaboration/Communication

[Overview of survey]([https://lab.realfoodcampaign.org/rfc-food-soil-survey-2019)\\
[GitLab](https://gitlab.com/our-sci/rfc-docs/-/tree/master)
[Project Status and Direction](https://lab.realfoodcampaign.org/yearly-plan-2020/)


## Main goals and deliverable

- investigate the amount of variation and causes of variation of nutrient density in crops
- identify ways to deliver nutrient density information in real time to farmers, consumers, and other parts of the supply chain.
- ultimately, predict in-field / on-farm nutritional density in produce using an app --> predict nutrient levels (e.g., Polyphenols and Antioxidants) of produce in the field (upon measurement with Our Sci reflectometer)

Objectives and status also layed out in (grant)[https://docs.google.com/document/d/1nHS-S44fyTQWrnddU-ROIFZW0rKQ3ewnf-0Yg_Y9Pyg/edit?usp=sharing] 


## Lab

[Lab protocols](https://docs.google.com/document/d/1cZ2QzDeds-UAiLPyJox4WCPKM_l0UOzbgFRoyCEyXsk/edit?usp=sharing)
- spectroscopy data ([selection of spectral ranges by James Frame](https://docs.google.com/spreadsheets/d/1akTy7BDZkQzCl9PbkOlstN4ieeR03wQBnlgsIS-qjR8/edit?usp=sharing))
  - SIWARE NIR 
  - open source matrix reflectometer (Our Sci), readings in range 365-940nm
- tissue
- juice


## Data

[2019 Survey results](https://gitlab.com/our-sci/rfc-docs/-/tree/master/2019)

- Brix is the sugar content in aqueous solution; one degree Brix is 1 gram of sucrose in 100 grams of solution and represents the strength of the solution as percentage by mass
- How are Polyphenols and Antioxidants measured?
- Is Dry.Mass in relation to some Fresh.Mass? 

### Additional data sources:
- USDA nutrition data


## Analysis



Load in browser: [dataAnalysis.html](./dataAnalysis.html)

